@Rem	myEnvironment defines the variables used for Adempiere
@Rem	Do not edit directly - use RUN_setup
@Rem	
@Rem	$Id: myEnvironmentTemplate.bat,v 1.12 2005/01/22 21:59:15 jjanke Exp $

@Echo Setting myEnvironment ....
@Rem	Clients only needs
@Rem		CYPRUS_HOME
@Rem		JAVA_HOME 
@Rem	Server install needs to check
@Rem		CYPRUS_DB_NAME	(for Oracle)
@Rem		passwords

@Rem 	Homes ...
@SET CYPRUS_HOME=@CYPRUS_HOME@
@SET JAVA_HOME=@JAVA_HOME@


@Rem	Database ...
@SET CYPRUS_DB_SERVER=@CYPRUS_DB_SERVER@
@SET CYPRUS_DB_USER=@CYPRUS_DB_USER@
@SET CYPRUS_DB_PASSWORD=@CYPRUS_DB_PASSWORD@
@SET CYPRUS_DB_URL=@CYPRUS_DB_URL@
@SET CYPRUS_DB_PORT=@CYPRUS_DB_PORT@

@Rem	Oracle specifics
@SET CYPRUS_DB_PATH=@CYPRUS_DB_PATH@
@SET CYPRUS_DB_NAME=@CYPRUS_DB_NAME@
@SET CYPRUS_DB_SYSTEM=@CYPRUS_DB_SYSTEM@

@Rem	Homes(2)
@SET CYPRUS_DB_HOME=@CYPRUS_HOME@\utils\@CYPRUS_DB_TYPE@
@SET JBOSS_HOME=@CYPRUS_HOME@\jboss

@Rem	Apps Server
@SET CYPRUS_APPS_TYPE=@CYPRUS_APPS_TYPE@
@SET CYPRUS_APPS_SERVER=@CYPRUS_APPS_SERVER@
@SET CYPRUS_JNP_PORT=@CYPRUS_JNP_PORT@
@SET CYPRUS_WEB_PORT=@CYPRUS_WEB_PORT@
@SET CYPRUS_APPS_DEPLOY=@CYPRUS_APPS_TYPE@
@Rem	SSL Settings
@SET CYPRUS_SSL_PORT=@CYPRUS_SSL_PORT@
@SET CYPRUS_KEYSTORE=@CYPRUS_KEYSTORE@
@SET CYPRUS_KEYSTOREWEBALIAS=@CYPRUS_KEYSTOREWEBALIAS@
@SET CYPRUS_KEYSTOREPASS=@CYPRUS_KEYSTOREPASS@

@Rem	etc.
@SET CYPRUS_FTP_SERVER=@CYPRUS_FTP_SERVER@
@SET CYPRUS_FTP_USER=@CYPRUS_FTP_USER@

@Rem	Java
@SET CYPRUS_JAVA=@JAVA_HOME@\bin\java
@SET CYPRUS_JAVA_OPTIONS=@CYPRUS_JAVA_OPTIONS@ -DCYPRUS_HOME=@CYPRUS_HOME@
@SET CLASSPATH="@CYPRUS_HOME@\lib\Cyprus.jar;@CYPRUS_HOME@\lib\CyprusCLib.jar;"

@Rem Save Environment file
@if (%1) == () copy myEnvironment.bat myEnvironment_%RANDOM%.bat /Y 

